version: "3.1"

services:
  app:
    container_name: app-be
    image: store-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - prod.env
    ports:
      - '5000:5000'
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    networks:
      - tris-web

  mongodb1:
    image: mongo:7.0.8
    container_name: mongo1
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    links:
      - mongodb3
      - mongodb2
    restart: always
    ports:
      - "30001:27017"
    volumes:
      - app-db-data-mongodb1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - tris-web

  mongodb2:
    image: mongo:7.0.8
    container_name: mongo2
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    restart: always
    expose:
      - 27017
    ports:
      - "30002:27017"
    volumes:
      - app-db-data-mongodb2:/data/db
    networks:
    - tris-web

  mongodb3:
    image: mongo:7.0.8
    container_name: mongo3
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    restart: always
    ports:
      - "30003:27017"
    volumes:
      - app-db-data-mongodb3:/data/db
    networks:
      - tris-web

volumes:
  app-db-data-mongodb1:
  app-db-data-mongodb2:
  app-db-data-mongodb3:

networks:
  tris-web:
