version: "3.1"

services:
  mongo7:
    image: mongo:7.0.8
    container_name: mongo7
    restart: always
    command: ["--bind_ip_all", "--replSet", "myRS"]
    links:
      - mongo9
      - mongo8
    ports:
      - "30007:27017"
    volumes:
      - app-db-data-mongo7:/data/db
    networks:
      - tris-web


  mongo8:
    image: mongo:7.0.8
    container_name: mongo8
    restart: always
    command: ["--bind_ip_all", "--replSet", "myRS"]
    ports:
      - "30008:27017"
    volumes:
      - app-db-data-mongo8:/data/db
    networks:
      - tris-web

  mongo9:
      image: mongo:7.0.8
      container_name: mongo9
      restart: always
      command: ["--bind_ip_all", "--replSet", "myRS"]
      ports:
        - "30009:27017"
      volumes:
        - app-db-data-mongo9:/data/db
      networks:
        - tris-web

volumes:
  app-db-data-mongo7:
  app-db-data-mongo8:
  app-db-data-mongo9:

networks:
  tris-web:
    external: true
