name: Pipeline CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build docker image
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)
          IMAGE_NAME=ghcr.io/${{ secrets.GH_USERNAME }}/store-backend/${COMMIT_ID}
          docker build -t $IMAGE_NAME .

      - name: Push to GitHub Container Registry
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)
          IMAGE_NAME=ghcr.io/${{ secrets.GH_USERNAME }}/store-backend/${COMMIT_ID}
          docker push $IMAGE_NAME