name: Pipeline CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login DockerHub
        uses: actions/checkout@v3
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build docker image
        run: docker build -t tridezpai/cicd-store-backend .

      - name: Push to DockerHub
        run: docker push tridezpai/cicd-store-backend:latest


