name: Pipeline CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login DockerHub
        uses: actions/checkout@v4
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USER_REPO}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_ACCESS_TOKEN}}
          run: docker login  -u $DOCKER_USER_REPO -p $DOCKER_ACCESS_TOKEN

      - name: Build docker image
        run: docker build -t cicd-store-backend .

      - name: Push to DockerHub
        run: docker push cicd-store-backend:latest


